import { inferDirectoryCategory } from "../category-map";
import type { ImportedVenue, VenueSearchResult } from "../types";
const GOOGLE_TEXT_SEARCH_URL = "https://places.googleapis.com/v1/places:searchText";
const GOOGLE_PLACE_URL = "https://places.googleapis.com/v1/places";
const PAGE_SIZE = 20; const MAX_PAGES_PER_QUERY = 3; const NEXT_PAGE_DELAY_MS = 1500;
const SEARCH_FIELD_MASK = ["places.id","places.displayName","places.formattedAddress","places.location","places.websiteUri","places.nationalPhoneNumber","places.rating","places.primaryType","places.types","places.googleMapsUri","nextPageToken"].join(",");
const DETAIL_FIELD_MASK = ["id","displayName","formattedAddress","location","websiteUri","nationalPhoneNumber","rating","primaryType","types","googleMapsUri","editorialSummary","regularOpeningHours","photos"].join(",");
const DEFAULT_CITY = "Lancaster, PA";
const DEFAULT_QUERIES = ["restaurants in Lancaster, PA","coffee shops in Lancaster, PA","bars in Lancaster, PA","music venues in Lancaster, PA","art galleries in Lancaster, PA","event venues in Lancaster, PA","breweries in Lancaster, PA","bakeries in Lancaster, PA","bookstores in Lancaster, PA","boutiques in Lancaster, PA"];
type GooglePlace = { id?: string; displayName?: { text?: string }; formattedAddress?: string; location?: { latitude?: number; longitude?: number }; websiteUri?: string; nationalPhoneNumber?: string; rating?: number; primaryType?: string; types?: string[]; googleMapsUri?: string; editorialSummary?: { text?: string }; regularOpeningHours?: { weekdayDescriptions?: string[] }; photos?: Array<{ name?: string }>; };
function getApiKey(): string { const key = process.env.GOOGLE_PLACES_API_KEY || process.env.GOOGLE_MAPS_API_KEY; if (!key) throw new Error("Missing GOOGLE_PLACES_API_KEY or GOOGLE_MAPS_API_KEY"); return key; }
function sleep(ms: number) { return new Promise((resolve) => setTimeout(resolve, ms)); }
function buildQueries(location?: string, query?: string) { const city = (location || DEFAULT_CITY).trim(); if (query?.trim()) return query.split(/[\n|,]+/).map((item) => item.trim()).filter(Boolean).map((item) => (/\bin\s+/i.test(item) ? item : `${item} in ${city}`)); return DEFAULT_QUERIES.map((item) => item.replace(DEFAULT_CITY, city)); }
async function searchTextPage(params: { apiKey: string; textQuery: string; pageToken?: string; pageSize?: number; }) { const body: Record<string, unknown> = { textQuery: params.textQuery, pageSize: params.pageSize || PAGE_SIZE, languageCode: "en", regionCode: "US" }; if (params.pageToken) body.pageToken = params.pageToken; const response = await fetch(GOOGLE_TEXT_SEARCH_URL, { method: "POST", headers: { "Content-Type": "application/json", "X-Goog-Api-Key": params.apiKey, "X-Goog-FieldMask": SEARCH_FIELD_MASK }, body: JSON.stringify(body), cache: "no-store" }); if (!response.ok) throw new Error(`Google Places request failed (${response.status} ${response.statusText}): ${await response.text()}`); return (await response.json()) as { places?: GooglePlace[]; nextPageToken?: string; }; }
async function getPlaceDetails(apiKey: string, placeId: string) { const response = await fetch(`${GOOGLE_PLACE_URL}/${encodeURIComponent(placeId)}`, { headers: { "X-Goog-Api-Key": apiKey, "X-Goog-FieldMask": DETAIL_FIELD_MASK }, cache: "no-store" }); if (!response.ok) throw new Error(`Google Place details request failed (${response.status} ${response.statusText}): ${await response.text()}`); return (await response.json()) as GooglePlace; }
function normalizePlace(place: GooglePlace): ImportedVenue | null { const externalId = place.id?.trim() || ""; const name = place.displayName?.text?.trim() || ""; if (!externalId || !name) return null; const rawCategories = Array.from(new Set([...(place.types || []), place.primaryType || ""].filter(Boolean).map((value) => value.replace(/_/g, " ")))); return { source: "google", externalId, name, address: place.formattedAddress || null, latitude: typeof place.location?.latitude === "number" ? place.location.latitude : null, longitude: typeof place.location?.longitude === "number" ? place.location.longitude : null, website: place.websiteUri || place.googleMapsUri || null, phone: place.nationalPhoneNumber || null, rating: typeof place.rating === "number" ? place.rating : null, rawCategories, category: inferDirectoryCategory({ category: place.primaryType?.replace(/_/g, " ") || rawCategories[0] || null, rawCategories, name }), description: place.editorialSummary?.text?.trim() || null, mapsUrl: place.googleMapsUri || null, hours: place.regularOpeningHours?.weekdayDescriptions || null, photoNames: (place.photos || []).map((photo) => photo.name).filter((value): value is string => Boolean(value)).slice(0, 6) }; }
function isLancasterArea(venue: ImportedVenue) { const haystack = `${venue.name} ${venue.address || ""} ${(venue.rawCategories || []).join(" ")}`.toLowerCase(); return ["lancaster, pa","lancaster pa","lititz","millersville","manheim","east petersburg","landisville","strasburg"].some((term) => haystack.includes(term)); }
function mergeVenue(existing: ImportedVenue, incoming: ImportedVenue): ImportedVenue { return { ...existing, website: existing.website || incoming.website || null, phone: existing.phone || incoming.phone || null, rating: existing.rating ?? incoming.rating ?? null, rawCategories: Array.from(new Set([...(existing.rawCategories || []), ...(incoming.rawCategories || [])])), category: existing.category || incoming.category || null, address: existing.address || incoming.address || null, latitude: existing.latitude ?? incoming.latitude ?? null, longitude: existing.longitude ?? incoming.longitude ?? null, description: existing.description || incoming.description || null, mapsUrl: existing.mapsUrl || incoming.mapsUrl || null, hours: existing.hours?.length ? existing.hours : incoming.hours || null, photoNames: existing.photoNames?.length ? existing.photoNames : incoming.photoNames || null }; }
export async function importGoogleVenues(params: { location?: string; query?: string } = {}): Promise<ImportedVenue[]> { const apiKey = getApiKey(); const queries = buildQueries(params.location, params.query); const byId = new Map<string, ImportedVenue>(); for (const textQuery of queries) { let pageToken: string | undefined; let page = 0; do { const data = await searchTextPage({ apiKey, textQuery, pageToken }); const normalized = (data.places || []).map(normalizePlace).filter((venue): venue is ImportedVenue => Boolean(venue)).filter(isLancasterArea); for (const venue of normalized) { const existing = byId.get(venue.externalId); byId.set(venue.externalId, existing ? mergeVenue(existing, venue) : venue); } page += 1; pageToken = data.nextPageToken; if (pageToken && page < MAX_PAGES_PER_QUERY) await sleep(NEXT_PAGE_DELAY_MS); else pageToken = undefined; } while (pageToken); } return Array.from(byId.values()).sort((a, b) => a.name.localeCompare(b.name)); }
export async function searchGooglePlaces(params: { query: string; location?: string; limit?: number; }): Promise<VenueSearchResult[]> { const query = params.query.trim(); if (!query) return []; const apiKey = getApiKey(); const city = (params.location || DEFAULT_CITY).trim(); const data = await searchTextPage({ apiKey, textQuery: /\bin\s+/i.test(query) ? query : `${query} in ${city}`, pageSize: Math.min(Math.max(params.limit || 8, 1), 10) }); return (data.places || []).map(normalizePlace).filter((venue): venue is ImportedVenue => Boolean(venue)).filter(isLancasterArea).slice(0, Math.min(Math.max(params.limit || 8, 1), 10)).map((venue) => ({ externalId: venue.externalId, name: venue.name, address: venue.address ?? null, category: venue.category ?? null, rawCategories: venue.rawCategories || [] })); }
export async function getGoogleVenueByPlaceId(placeId: string): Promise<ImportedVenue | null> { const cleanId = placeId.trim(); if (!cleanId) return null; const venue = normalizePlace(await getPlaceDetails(getApiKey(), cleanId)); return venue && isLancasterArea(venue) ? venue : null; }
export async function resolveGoogleVenueByName(params: { query: string; location?: string }): Promise<ImportedVenue | null> { const query = params.query.trim(); if (!query) return null; const top = (await searchGooglePlaces({ query, location: params.location, limit: 1 }))[0]; return top?.externalId ? getGoogleVenueByPlaceId(top.externalId) : null; }
